services:
  backend:
    build:
      context: ./backend
    container_name: arame-backend
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ./backend/uploads:/app/uploads
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: arame-frontend
    depends_on:
      - backend
    ports:
      - "5173:80"
    restart: unless-stopped
